on: [push, pull_request]

name: Go
jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download
    - name: Test with -race
      run: go test -race -count=1 ./...
    - name: Integration test
      if: matrix.platform == 'ubuntu-latest' && startsWith(matrix.go-version, '1.17')
      run: |
        sudo modprobe nfnetlink_queue
        sudo ip6tables -I OUTPUT -p ipv6-icmp -j NFQUEUE --queue-num 100
        sudo iptables -I OUTPUT -p icmp -j NFQUEUE --queue-num 100
        go test -v -tags integration -exec=sudo -count=1 ./...
    - name: golint
      if: matrix.platform == 'ubuntu-latest'
      # https://github.com/actions/setup-go/issues/14
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        golint -set_exit_status $(go list ./... | grep -v internal/unix)
    - name: staticcheck.io
      if: matrix.platform == 'ubuntu-latest'
      # https://github.com/actions/setup-go/issues/14
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u honnef.co/go/tools/cmd/staticcheck
        staticcheck -checks=all .
        # ignore should not use ALL_CAPS in Go names in internal/
        staticcheck -checks=all,-ST1003 ./internal/...
